name: Pages

on:
  push:
    branches: [ "edge" ]

  workflow_dispatch:

jobs:
  pages-build:
    name: Pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install doxygen
          curl -L -o premake5.tar.gz https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-linux.tar.gz && mkdir premake5 && tar -xf premake5.tar.gz -C premake5
          echo "${GITHUB_WORKSPACE}/premake5" >> $GITHUB_PATH
      
      - name: Test
        run: |
          premake5 check
          premake5 --test gmake
          make clean test

      - name: Build
        run: |
          premake5 --modules=ctrl --static gmake
          make config=release_web clean web-frontend

      - name: Docs
        run: premake5 doc

      - name: Package
        run: |
          mkdir gh-pages
          echo -n app.virtualxt.org > gh-pages/CNAME
          cp -r docs gh-pages
          cp -r build/web/* gh-pages

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          branch: gh-pages
          folder: gh-pages
