name: RasberryPi

on:
  push:
    branches: [ "develop", "edge", "release" ]
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

env:
  VXT_VERSION: 1.2.0
  
jobs:
  rpi-build:
    name: RPI3
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install cppcheck gcc-arm-none-eabi
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default && unzip butler.zip -d butler
          curl -L -o premake5.tar.gz https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-linux.tar.gz && mkdir premake5 && tar -xf premake5.tar.gz -C premake5
          echo "${GITHUB_WORKSPACE}/butler" >> $GITHUB_PATH
          echo "${GITHUB_WORKSPACE}/premake5" >> $GITHUB_PATH

      - name: Setup Circle
        run: |
          curl -L -o circle.zip https://github.com/virtualxt/circle/archive/refs/heads/master.zip && unzip circle.zip
          cd circle-master
          ./configure -r 3 --c++17 -f
          ./makeall

      - name: Test & Check
        run: |
          premake5 check
          premake5 --test gmake
          make test
          make clean         
        
      - name: Build
        run: |
          export CIRCLEHOME="${GITHUB_WORKSPACE}/circle-master"
          make -C "${CIRCLEHOME}/boot"
          make -C "${CIRCLEHOME}/addon/fatfs"
          make -C "${CIRCLEHOME}/addon/SDCard"
          make -C "${GITHUB_WORKSPACE}/front/rpi"

      - name: Package
        run: |
          export CIRCLEHOME="${GITHUB_WORKSPACE}/circle-master"
          ./tools/package/itch/package.rasberrypi.sh

      - name: Deploy
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: if [[ $GITHUB_REF_NAME =~ ^(edge|release)$ ]]; then ./tools/package/itch/push-rasberrypi.sh; fi
